### ISSUE TITLE
Solution branch out of sync with master / not intended for this repo

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-enumerable-io#11]
Some of these exercises are the same as the https://github.com/ga-wdi-boston/ruby-array-methods ones.

**Comment by gaand** [comment]
How is reading from a file similar to anything in that repository?

There are code files that are used by array methods in this repository, but in the array methods talk, they shouldn't be covered accept to say that that's how we get the arrays to work with.

**Comment by raq929** [comment]
It's not! I made this comment while looking at the solution branch, which has an old README which _is_ substantially similar to ruby-array-methods. Changing the title of this issue accordingly.

**Comment by raq929** [comment]
It looks like this repo was cloned from ruby-array-methods, and the solution branch was not updated.

**Comment by gaand** [comment]
Ah, yes that's true.  I thought I'd corrected that.  The solution branch is probably the solution to `ruby-enumerable` as delivered to cohort 009.

I broke `ruby-enumerable` into `ruby-array-methods`, `ruby-enumerable-builtins`, `ruby-enumerable-comparable`, and `ruby-enumerable-io`.  Everything that needed to happen after that hasn't yet.

**Comment by raq929** [comment]
Related to issue #8
