### ISSUE TITLE
Remove code in bin/people_array in master branch

### ISSUE THREAD

**Issue by danman01** [ga-wdi-boston/ruby-enumerable-io#19]
Or maybe not...possibly the readme is outdated.

This is a note from a convo I had about prepping this lesson with Jeff.

We will investigate more and comment here.

File in question:
https://github.com/ga-wdi-boston/ruby-enumerable-io/blob/master/bin/people_array.rb

**Comment by jrhorn424** [comment]
Is this a scaffolding concern, or just a mistake with git and branches?

**Comment by jrhorn424** [comment]
I should have read my own commit message:

>Improve starter code
>Add solution from [Ruby Array Methods](https://github.com/ga-wdi-boston/ruby-array-methods)
